name: getx_assist_analyzer_plugin
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  analyzer: ^2.6.0
  analyzer_plugin: ^0.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
